### ISSUE TITLE
UI is not open source

### ISSUE THREAD

**Issue by xiezhaohui** [streampipes/streampipes-ce#2]
I can not find UI code source? UI is not open source?Where is UI code source?thank you

**Comment by dominikriemer** [comment]
Hi,
you can find the UI on Docker Hub: https://hub.docker.com/r/streampipes/ui
We are currently working on preparing the UI source code for a public release, stay tuned!

**Comment by hannosta** [comment]
Perhaps this copy past error can be corrected:
The first Reference Point Latitude should be Reference Point Longitude.
![latitude-to-longitude](https://user-images.githubusercontent.com/18658362/53868673-d3d58000-3ff6-11e9-8140-cc85007e730e.png)
