### ISSUE TITLE
Could not stop all pipeline elements

### ISSUE THREAD

**Issue by hannosta** [streampipes/streampipes-ce#4]
Hi, I have the problem that I can't stop a pipeline. Most likely I just used the Pipeline Editor wrong. 
This is my pipeline:
![pipeline](https://user-images.githubusercontent.com/18658362/53868925-66761f00-3ff7-11e9-87e0-1084c7b0770f.png)
This is the error when I try to stop the pipeline:
![error](https://user-images.githubusercontent.com/18658362/53868962-7beb4900-3ff7-11e9-9418-352c3c2bc5b4.png)

**Comment by tenthe** [comment]
You didn't use the pipeline editor wrong, we should have provided an error message, when you tried to store the pipeline.
Currently we just support a single pipeline within the pipeline editor. You can add splits and merges to this pipeline, but in your example you have two independent pipelines.

Thank you for your report, we will add the validation step in future releases.

**Comment by dominikriemer** [comment]
Thanks for your feedback!
Based on your feedback, we've implemented a feature that provides interactive hints on pipeline validation errors such as missing sinks or multiple independent pipelines in the assembly (see the screenshot below). This should improve the user guidance while creating pipelines.

The feature is already fully implemented in our dev branch and will be part of the upcoming release 0.61.0. We hope you'll like this extension!

![streampipes-error-message](https://user-images.githubusercontent.com/33908476/53991959-03d26f80-412c-11e9-9063-aa98ac9142ca.png)

**Comment by dominikriemer** [comment]
Part of release v0.61.0
