### ISSUE TITLE
Frontend copy past mistake

### ISSUE THREAD

**Issue by hannosta** [streampipes/streampipes-ce#5]
Perhaps this copy past error can be corrected:
The first Reference Point Latitude should be Reference Point Longitude.
![latitude-to-longitude](https://user-images.githubusercontent.com/18658362/53869285-367b4b80-3ff8-11e9-9626-3f26c91dd756.png)

**Comment by tenthe** [comment]
Thank you for your bug report.
This looks like a problem with the description of the source.
Make sure that latitude and longitude have the correct label and domain property.

I will close this issue. If it still does not work after changing the source feel free to re-open it again.
